# docker-compose.yml
# tip: run `docker compose config` to validate this file

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ipam
      POSTGRES_PASSWORD: ipam
      POSTGRES_DB: ipam
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ipam -d ipam"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://ipam:ipam@db:5432/ipam
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  web:
    build:
      context: ./frontend
    environment:
      INTERNAL_API_BASE: http://api:8000        # used by SSR inside the container
      NEXT_PUBLIC_API_BASE: http://localhost:8000  # used by the browser on your PC
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy

volumes:
  db_data:
